name: Push project build to JFrog Artifactory

on:
  push:
    branches:
      - main
  tags:
      - '*pre'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # This action checks out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # This action sets up the JFrog CLI with the Artifactory URL and access token
      - uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_ARTIFACTORY_KEY: ${{ secrets.JFROG_DEV_ROBOT_API_KEY }}

      # This action creates a new test file and uploads it to Artifactory
      - name: Push Build to Artifactory
        run: |
          export BUILD_NAME="g3"
          export BUILD_MODULE="main"
          export BUILD_NUMBER="1"

          # export PATH_TO_DIRECTORY="name/version/dates"

          jf rt upload "test.txt" g --build-name $BUILD_NAME --build-number $BUILD_NUMBER --module $BUILD_MODULE

      # This action publishes the build information to Artifactory, and retains the latest 10 builds
      - name: Build to Artifactory
        run: |
          jfrog rt u g g3/g3
          jf rt build-publish $BUILD_NAME $BUILD_NUMBER

          jf rt bdi c --max-builds=10
